version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.<your-region>.amazonaws.com
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  build:
    commands:
      - docker build -t my-app-repo .
      - docker tag my-app-repo:latest <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/my-app-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/my-app-repo:latest
      - echo Build completed on `date`
